### PR TITLE
make hits required

### PR DESCRIPTION
**Pull request by TomWoodward**

### CODE REVIEW

**Comment by steveburkett** [comment]
we should prob. add a top level controller test for this too eh?  one that tests for an empty response, meeting the requirement of hits being required?

**Comment by jpslav** [comment]
@steveburkett do you mean testing that elasticsearch returns an empty hits array?

**Comment by TomWoodward** [comment]
@steveburkett @jpslav not sure if that is necessary since its really testing elasticsearch

**Comment by jpslav** [comment]
@TomWoodward steve brought up a good point that we should be making sure that what we give back to our clients matches the API spec we are publishing, so I made another card for steve to implement some better verification that we are getting from ES and putting into our API output is actually what we publish.

**Pull request merged**
